version: '3.7'
services:
  bigquery:
    platform: linux/x86_64
    image: ghcr.io/goccy/bigquery-emulator:latest
    ports:
      - "9050:9050"
      - "9060:9060"
    volumes:
      - ./data:/data
    command: --project=local-project --data-from-yaml=/data/data.yaml

  bq-ui:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BIGQUERY_PROJECT_ID=local-project
      - BIGQUERY_EMULATOR_HOST=bigquery:9050
    depends_on:
      - bigquery
